repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "(^static/|/static/|^fobi/|.md$|.django.po$|.csv$)"
      - id: end-of-file-fixer
        exclude: "(^static/|/static/|^fobi/)"
      - id: debug-statements
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ['-iii', '-ll', "-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.6
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
