name: Django CI/CD Workflow

on:
  release:
    types: [published]
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python 3.8
        run: uv python install 3.8.19
      - name: Install the project
        run: uv sync
      - name: Run pre-commit
        run: uv run pre-commit run --all-files --config .pre-commit-config.ci.yaml
      - name: Run tests
        run: uv run python -m unittest discover tests
